# Valence Word Exploration

In [3]:
%cd /Users/steed/caliskan/git/ieat

/Users/steed/caliskan/git/ieat

In [9]:
import pandas as pd

valence_words = pd.read_csv("data/bgb_pleasant-words.csv").set_index("word")
q = 0.8
p = 0.8
m = 0.25
valence_words[["pleasantness", "imagery", "frequency"]].to_latex("output/valence.tex")
valence_words

,pleasantness_male,pleasantness_female,pleasantness,imagery_male,imagery_female,imagery,frequency_male,frequency_female,frequency
word,,,,,,,,,
abuse,1.62,1.44,1.53,2.93,3.60,3.31,2.69,3.26,3.00
accident,1.54,1.47,1.51,4.00,4.14,4.08,3.45,3.47,3.46
achievement,4.51,4.63,4.57,2.58,3.34,3.02,3.10,3.65,3.40
adorable,4.33,4.47,4.40,3.33,3.63,3.50,2.66,3.76,3.25
affectionate,4.49,4.64,4.56,3.08,3.74,3.46,3.00,3.79,3.43
...,...,...,...,...,...,...,...,...,...
window,3.68,3.44,3.57,4.63,4.74,4.69,3.83,4.09,3.97
wine,3.80,3.97,3.88,4.44,4.71,4.59,3.41,3.79,3.62
wise,4.47,4.25,4.36,2.93,3.17,3.06,3.10,2.94,3.02
woman,4.47,4.00,4.20,4.74,4.63,4.68,4.31,4.50,4.41
world,3.97,4.08,4.03,4.30,4.29,4.29,3.79,3.91,3.86

In [12]:
# high pleasantness
valence_words[
    (valence_words.pleasantness > valence_words.pleasantness.quantile(q=q)) &
    (valence_words.imagery > valence_words.imagery.quantile(q=p))
].sort_values("imagery", ascending=False)[["pleasantness", "imagery"]].head(5).to_latex("output/valence.tex")

In [11]:
# low pleasantness
valence_words[
    (valence_words.pleasantness < valence_words.pleasantness.quantile(q=(1-q))) &
    (valence_words.imagery > valence_words.imagery.quantile(q=p-m))
].sort_values("imagery")[["pleasantness", "imagery"]]

           pleasantness  imagery
word
killer             1.20     3.82
fungus             1.60     3.82
rape               1.22     3.87
morgue             1.50     3.89
crucify            1.42     3.90
death              1.47     3.93
slum               1.46     3.94
devil              1.37     3.95
flabby             1.60     3.95
whore              1.60     4.02
burial             1.42     4.02
riot               1.60     4.08
accident           1.51     4.08
corpse             1.51     4.11
hitler             1.30     4.13
bomb               1.51     4.16
war                1.39     4.18
crash              1.56     4.18
slave              1.55     4.24
obesity            1.60     4.26
vomit              1.20     4.38
funeral            1.43     4.42
jail               1.51     4.44
roach              1.58     4.44
coffin             1.53     4.48
cockroach          1.55     4.49
prison             1.50     4.50